# Generated by Django 5.0.4 on 2024-09-26 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('issue', models.CharField(choices=[('Member Plan', 'Member Plan'), ('Equipments', 'Equipments'), ('Gym Environment', 'Gym Environment'), ('Lost Items', 'Lost Items'), ('Others', 'Others')], max_length=20)),
                ('message', models.TextField()),
                ('enquiry_date', models.DateField(default=datetime.date.today)),
                ('is_resolved', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
            ],
        ),
    ]
