# Generated by Django 5.1.2 on 2024-11-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_remove_memberenquiry_enquiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
