# Generated by Django 5.0.2 on 2024-11-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0009_message_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
